version: '3.9'

services:

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch
    build:
      context: ./
      dockerfile: ./elasticsearch/Dockerfile
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    environment:
      - cluster.name=docker-elasticsearch-cluster
      - node.name=node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk_stack
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

networks:
  elk_stack:
    driver: bridge

volumes:
  elasticsearch:
    driver: local
