version: '3.9'

services:

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch
    build:
      context: ./
      dockerfile: ./elasticsearch/Dockerfile
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    environment:
      - discovery.type=single-node
      - cluster.name=docker-elasticsearch-cluster
      - node.name=node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk_stack
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: kibana
    build:
      context: ./
      dockerfile: ./kibana/Dockerfile
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk_stack

networks:
  elk_stack:
    driver: bridge

volumes:
  elasticsearch:
    driver: local
